from pyspark.sql.types import (
    BooleanType,
    DateType,
    FloatType,
    IntegerType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    DoubleType,
    LongType
)

class F1Schemas:
    """
    FAST F1 SCHEMA
    """
    #Schema for telementry data
    telemetry_schema = StructType([
        StructField("PermanentNumber", StringType(), True), # cast to int
        StructField("Date", StringType(), True), # cast to timestamp
        StructField("Time", StringType(), True),    # Have to type casting it to float type later
        StructField("SessionTime", StringType(), True),  # Have to type casting it to float type later
        StructField("Speed", DoubleType(), True),
        StructField("Throttle", DoubleType(), True),
        StructField("Brake", BooleanType(), True),
        StructField("RPM", DoubleType(), True), #Cast to int
        StructField("nGear", DoubleType(), True), #Cast to int
        StructField("DRS", DoubleType(), True), #Cast to int
        StructField("Distance", DoubleType(), True),
        StructField("X", DoubleType(), True),
        StructField("Y", DoubleType(), True),
        StructField("Z", DoubleType(), True),
        StructField("Session_id", StringType(), True),
        StructField("Source", StringType(), True),
        StructField("Season", IntegerType(), True)
    ])

    #Schemas for Weather data
    weather_schema = StructType([
        StructField("Time", StringType(), True), # Have to type casting it to float type later
        StructField("AirTemp", DoubleType(), True),
        StructField("TrackTemp", DoubleType(), True),
        StructField("Humidity", DoubleType(), True),
        StructField("Rainfall", BooleanType(), True),
        StructField("WindSpeed", DoubleType(), True),
        StructField("WindDirection", DoubleType(), True), # cast to int
        StructField("Pressure", DoubleType(), True),
        StructField("Session_id", StringType(), True),
        StructField("Source", StringType(), True),
        StructField("Season", IntegerType(), True)
    ])

    #Schemas for Lap data
    lap_schema = StructType([
        StructField("Driver", StringType(), True),
        StructField("DriverNumber", StringType(), True), # Cast to int
        StructField("LapNumber", DoubleType(), True), #Cast to int
        StructField("LapTime", StringType(), True), # Have to type casting it to float type later
        StructField("LapStartTime", StringType(), True), # Have to type casting it to float type later
        StructField("Time", StringType(), True),
        StructField("Stint", DoubleType(), True), #Cast to int
        StructField("Compound", StringType(), True),
        StructField("TyreLife", DoubleType(), True), #Cast to int
        StructField("FreshTyre", BooleanType(), True),
        StructField("Sector1Time", StringType(), True), # Have to type casting it to float type later
        StructField("Sector2Time", StringType(), True), # Have to type casting it to float type later
        StructField("Sector3Time", StringType(), True), # Have to type casting it to float type later
        StructField("PitInTime", StringType(), True), # Have to type casting it to float type later
        StructField("PitOutTime", StringType(), True), # Have to type casting it to float type later
        StructField("TrackStatus", StringType(), True),
        StructField("IsAccurate", BooleanType(), True),
        StructField("Session_id", StringType(), True),
        StructField("Source", StringType(), True),
        StructField("Season", IntegerType(), True)
    ])

    """
    API-Jolpica
    """
    #Schema for Driver data
    driver_schema = StructType([
        StructField("driverId", StringType(), True),  #Racer ID generated by Jolpica to ensure uniqueness.
        StructField("permanentNumber", StringType(), True),  #Cast to int
        StructField("code", StringType(), True),
        StructField("givenName", StringType(), True),
        StructField("familyName", StringType(), True),
        StructField("dateOfBirth", DateType(), True),
        StructField("nationality", StringType(), True),
        StructField("source", StringType(), True)
    ]) 

    #Schema for Constructor data
    constructor_schema = StructType([
        StructField("constructorId", StringType(), True),
        StructField("name", StringType(), True),
        StructField("nationality", StringType(), True),
        StructField("source", StringType(), True)
    ])

    time_schema = StructType([
        StructField("millis", StringType(), True), #Cast to float
        StructField("time", StringType(), True) #- need to be consider
    ])

    average_speed_schema = StructType([
        StructField("units", StringType(), True),
        StructField("speed", StringType(), True) #Cast to float
    ])

    fastest_lap_schema = StructType([
        StructField("rank", StringType(), True), #Cast to int
        StructField("lap", StringType(), True), #Cast to int
        StructField("Time", StructType([
            StructField("time", StringType(), True),
        ])),
        StructField("AverageSpeed", average_speed_schema, True)
    ])

    #Schema for race result
    result_schema = StructType([
        StructField("number", StringType(), True), #Cast to int
        StructField("position", StringType(), True), #Cast to int
        StructField("points", StringType(), True), #Cast to float
        StructField("Driver", driver_schema, True),
        StructField("Constructor", constructor_schema, True),
        StructField("grid", StringType(), True), #Cast to int
        StructField("laps", StringType(), True), #Cast to int
        StructField("status", StringType(), True),
        StructField("Time", time_schema, True),
        StructField("FastestLap", fastest_lap_schema, True),
        StructField("race_id", StringType(), True),
        StructField("source", StringType(), True),
        StructField("season", IntegerType(), True)
    ])


    location_schema = StructType([
        StructField("lat", StringType(), True), #Cast to float
        StructField("long", StringType(), True), #Cast to float
        StructField("locality", StringType(), True),
        StructField("country", StringType(), True)
    ])

    #Schema for circuit data
    circuit_schema = StructType([
        StructField("circuitId", StringType(), True),
        StructField("circuitName", StringType(), True),
        StructField("Location", location_schema, True)
    ])

    #Schema for race data
    race_schema = StructType([
        StructField("season", StringType(), True), #Cast to int
        StructField("round", StringType(), True), #Cast to int
        StructField("raceName", StringType(), True),
        StructField("Circuit", circuit_schema, True),

        #Have to merge it later in silver layer
        StructField("date", StringType(), True),  # Only date data.
        StructField("time", StringType(), True),  # Only Time data.
        
        StructField("race_id", StringType(), True),
        StructField("source", StringType(), True)
    ])

    """
    StatsF1
    """

    #Schema for Driver data

    driver_statsf1_schema = StructType([
        StructField("Driver", StringType(), True),
        StructField("Constructor", StringType(), True),
        StructField("Engine_Manufacturer", StringType(), True),
        StructField("Best_Result", StringType(), True),
        StructField("Source", StringType(), True),
        StructField("Season", IntegerType(), True)
    ])

    #Schema for Car data
    car_statsf1_schema = StructType([
        StructField("Constructor", StringType(), True),
        StructField("Chassis", StringType(), True),
        StructField("Engine", StringType(), True),
        StructField("Source", StringType(), True),
        StructField("Season", IntegerType(), True)
    ])

    #Schema for Engine Supplier data
    engine_supplier_statsf1_schema = StructType([
        StructField("Engine_Manufacturer", StringType(), True),
        StructField("Nation", StringType(), True),
        StructField("Started_time", StringType(), True), #Only Year and cast tp int
        StructField("Source", StringType(), True)
    ])

    #Schema for Constructor data
    constructor_statsf1_schema = StructType([
        StructField("Constructor", StringType(), True),
        StructField("Nation", StringType(), True),
        StructField("Started_time", StringType(), True), #Only year and cast to int
        StructField("Source", StringType(), True)
    ])

    #Schema for Race Result data
    result_statsf1_schema = StructType([
        StructField("Race_id", StringType(), True),
        StructField("Position", StringType(), True),
        StructField("Driver_number", StringType(), True),
        StructField("Driver", StringType(), True),
        StructField("Chassis", StringType(), True),
        StructField("Engine_manufacturer", StringType(), True),
        StructField("Total_lap", StringType(), True), #Cast to int

        #Edit the data at the Silver layer to separate race time and the gap to the leader.
        #type casting to float
        StructField("Race_time", StringType(), True), 

        StructField("Source", StringType(), True)
    ])

    
