from pyspark.sql.types import (
    BooleanType,
    DateType,
    FloatType,
    IntegerType,
    StringType,
    StructField,
    StructType,
    TimestampType,
)

class F1Schemas:
    """
    FAST F1 SCHEMA
    """
    #Schema for telementry data
    telemetry_schema = StructType([
        StructField("PermanentNumber", StringType(), True),
        StructField("Date", TimestampType(), True),
        StructField("Time", StringType(), True),    # Have to type casting it to float type later
        StructField("SessionTime", StringType(), True),  # Have to type casting it to float type later
        StructField("Speed", FloatType(), True),
        StructField("Throttle", FloatType(), True),
        StructField("Brake", BooleanType(), True),
        StructField("RPM", IntegerType(), True),
        StructField("nGear", IntegerType(), True),
        StructField("DRS", IntegerType(), True),
        StructField("Distance", FloatType(), True),
        StructField("X", FloatType(), True),
        StructField("Y", FloatType(), True),
        StructField("Z", FloatType(), True),
        StructField("Session_id", StringType(), True),
        StructField("Source", StringType(), True),
        StructField("Season", IntegerType(), True)
    ])

    #Schemas for Weather data
    weather_schema = StructType([
        StructField("Time", StringType(), True), # Have to type casting it to float type later
        StructField("AirTemp", FloatType(), True),
        StructField("TrackTemp", FloatType(), True),
        StructField("Humidity", FloatType(), True),
        StructField("Rainfall", BooleanType(), True),
        StructField("WindSpeed", FloatType(), True),
        StructField("WindDirection", IntegerType(), True),
        StructField("Pressure", FloatType(), True),
        StructField("Session_id", StringType(), True),
        StructField("Source", StringType(), True),
        StructField("Season", IntegerType(), True)
    ])

    #Schemas for Lap data
    lap_schema = StructType([
        StructField("Driver", StringType(), True),
        StructField("DriverNumber", StringType(), True),
        StructField("LapNumber", IntegerType(), True),
        StructField("LapTime", StringType(), True), # Have to type casting it to float type later
        StructField("LapStartTime", StringType(), True), # Have to type casting it to float type later
        StructField("Time", StringType(), True),
        StructField("Stint", IntegerType(), True),
        StructField("Compound", StringType(), True),
        StructField("TyreLife", IntegerType(), True),
        StructField("FreshTyre", BooleanType(), True),
        StructField("Sector1Time", StringType(), True), # Have to type casting it to float type later
        StructField("Sector2Time", StringType(), True), # Have to type casting it to float type later
        StructField("Sector3Time", StringType(), True), # Have to type casting it to float type later
        StructField("PitInTime", StringType(), True), # Have to type casting it to float type later
        StructField("PitOutTime", StringType(), True), # Have to type casting it to float type later
        StructField("TrackStatus", StringType(), True),
        StructField("IsAccurate", BooleanType(), True),
        StructField("Session_id", StringType(), True),
        StructField("Source", StringType(), True),
        StructField("Season", IntegerType(), True)
    ])

    """
    API-Jolpica
    """
    #Schema for Driver data
    driver_schema = StructType([
        StructField("driverId", StringType(), True),  #Racer ID generated by Jolpica to ensure uniqueness.
        StructField("permanentNumber", IntegerType(), True),
        StructField("code", StringType(), True),
        StructField("givenName", StringType(), True),
        StructField("familyName", StringType(), True),
        StructField("dateOfBirth", DateType(), True),
        StructField("nationality", StringType(), True),
        StructField("source", StringType(), True)
    ]) 

    #Schema for Constructor data
    constructor_schema = StructType([
        StructField("constructorId", StringType(), True),
        StructField("name", StringType(), True),
        StructField("nationality", StringType(), True),
        StructField("source", StringType(), True)
    ])

    time_schema = StructType([
        StructField("millis", FloatType(), True),
        StructField("time", StringType(), True) #- need to be consider
    ])

    average_speed_schema = StructType([
        StructField("units", StringType(), True),
        StructField("speed", FloatType(), True)
    ])

    fastest_lap_schema = StructType([
        StructField("rank", IntegerType(), True),
        StructField("lap", IntegerType(), True),
        StructField("Time", StructType([
            StructField("time", StringType(), True),
        ])),
        StructField("AverageSpeed", average_speed_schema, True)
    ])

    #Schema for race result
    result_schema = StructType([
        StructField("number", IntegerType(), True),
        StructField("position", IntegerType(), True),
        StructField("points", FloatType(), True),
        StructField("Driver", driver_schema, True),
        StructField("Constructor", constructor_schema, True),
        StructField("grid", IntegerType(), True),
        StructField("laps", IntegerType(), True),
        StructField("status", StringType(), True),
        StructField("Time", time_schema, True),
        StructField("FastestLap", fastest_lap_schema, True),
        StructField("race_id", StringType(), True),
        StructField("source", StringType(), True),
        StructField("season", IntegerType(), True)
    ])


    location_schema = StructType([
        StructField("lat", FloatType(), True),
        StructField("long", FloatType(), True),
        StructField("locality", StringType(), True),
        StructField("country", StringType(), True)
    ])

    #Schema for circuit data
    circuit_schema = StructType([
        StructField("circuitId", StringType(), True),
        StructField("circuitName", StringType(), True),
        StructField("Location", location_schema, True)
    ])

    #Schema for race data
    race_schema = StructType([
        StructField("season", IntegerType(), True),
        StructField("round", IntegerType(), True),
        StructField("raceName", StringType(), True),
        StructField("Circuit", circuit_schema, True),

        #Have to merge it later in silver layer
        StructField("date", StringType(), True),  # Only date data.
        StructField("time", StringType(), True),  # Only Time data.
        
        StructField("race_id", StringType(), True),
        StructField("source", StringType(), True)
    ])

    """
    StatsF1
    """

    #Schema for Driver data

    driver_statsf1_schema = StructType([
        StructField("Driver", StringType(), True),
        StructField("Constructor", StringType(), True),
        StructField("Engine_Manufacturer", StringType(), True),
        StructField("Best_Result", StringType(), True),
        StructField("Source", StringType(), True),
        StructField("Season", IntegerType(), True)
    ])

    #Schema for Car data
    car_statsf1_schema = StructType([
        StructField("Constructor", StringType(), True),
        StructField("Chassis", StringType(), True),
        StructField("Engine", StringType(), True),
        StructField("Source", StringType(), True),
        StructField("Season", IntegerType(), True)
    ])

    #Schema for Engine Supplier data
    engine_supplier_statsf1_schema = StructType([
        StructField("Engine_Manufacturer", StringType(), True),
        StructField("Nation", StringType(), True),
        StructField("Started_time", IntegerType(), True), #Only Year
        StructField("Source", StringType(), True)
    ])

    #Schema for Constructor data
    constructor_statsf1_schema = StructType([
        StructField("Constructor", StringType(), True),
        StructField("Nation", StringType(), True),
        StructField("Started_time", IntegerType(), True), #Only year
        StructField("Source", StringType(), True)
    ])

    #Schema for Race Result data
    result_statsf1_schema = StructType([
        StructField("Race_id", StringType(), True),
        StructField("Position", StringType(), True),
        StructField("Driver_number", StringType(), True),
        StructField("Driver", StringType(), True),
        StructField("Chassis", StringType(), True),
        StructField("Engine_manufacturer", StringType(), True),
        StructField("Total_lap", IntegerType(), True),

        #Edit the data at the Silver layer to separate race time and the gap to the leader.
        #type casting to float
        StructField("Race_time", StringType(), True), 

        StructField("Source", StringType(), True)
    ])

    
